apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: spring-boot-server-angular-app
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/angular-app/spring-boot-server-angular-app@sha256:7c8fe154a2ebf42b7b353e628edcd3df4228a6e23f0802973056b05c2b426ad4
        name: my-java-springboot
        resources: {}
status: {}
