apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-angular-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-angular-app
    app.kubernetes.io/part-of: angular-app
  name: angular-15-client-angular-app
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: angular-15-client-angular-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: angular-15-client-angular-app
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/karthik-jk-tenant/angular-app/angular-15-client-angular-app@sha256:2144b9386a6c8cefaf8f4f4e70db34531ff9165c98b6674f3ac7674d664c1bb0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
