apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: angular-15-client-angular-app
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: angular-15-client-angular-app
    app.kubernetes.io/part-of: angular-app
  name: angular-15-client-angularr140
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: angular-15-client-angular-app
    weight: null
status: {}
